#!/bin/sh
times='0'
for i in `seq 50`;
    #做50次拨号循环，50次如果都没拨上也停止
do
    sleep 2
    wanip=$(ifconfig pppoe-wan 2> /dev/null | grep 'inet addr' | awk '{print $2}' | cut -d: -f2)
    #获取wan口ip
    sleep 2 
    pubip=$(wget -qO - ddns.oray.com/checkip|tr -cd [0-9.])
    #从网络获取公网IP
    echo "Public IP:" $pubip
    echo "WAN IP:" $wanip
    #显示IP
    if [ "$wanip" = "" ]||[ "$wanip" = "0.0.0.0" ]; then
    #如果获取的IP是无效，记为错误
        if [ "$times" -ge "3" ]&&[ "$wanip" = "" ]||[ "$wanip" = "0.0.0.0" ]; then
        #如果连续5次都还是没有获取到ip，重拨
            times='0'
            ifdown wan | ifup wan 
            sleep 2
            continue
        else
            times=`expr $times + 1`;
            echo "error times :" $times
            echo "waitting two seconds"
            sleep 2
        fi
    elif [ "$pubip" = "$wanip" ]; then
    #如果外网IP和本地IP相同，则保留IP
        echo "dial success"
        break

    else
    #如果获取的是内网IP，重拨
        echo "Intranet IP:" $wanip 
        echo "Redial ..."
        ifdown wan | ifup wan 
        sleep 2
    fi
done
